-- Dimensions continues : les règles produisent des deltas décimaux (traits, habituation).
-- L'index HNSW de memory (migration constraints) est volontairement conservé.

-- AlterTable
ALTER TABLE "character_state" ALTER COLUMN "energy" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "morale" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "popularity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "influence" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "reputation" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "effect" ALTER COLUMN "delta" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "value_after" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "relationship" ALTER COLUMN "trust" SET DEFAULT 30,
ALTER COLUMN "trust" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "affection" SET DEFAULT 0,
ALTER COLUMN "affection" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rivalry" SET DEFAULT 0,
ALTER COLUMN "rivalry" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "respect" SET DEFAULT 50,
ALTER COLUMN "respect" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fear" SET DEFAULT 0,
ALTER COLUMN "fear" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attraction" SET DEFAULT 0,
ALTER COLUMN "attraction" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "alliance" SET DEFAULT 0,
ALTER COLUMN "alliance" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "relationship_snapshot" ALTER COLUMN "trust" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "affection" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rivalry" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "respect" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fear" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attraction" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "alliance" SET DATA TYPE DOUBLE PRECISION;
