import type {
  CharacterStateRecord,
  EpochRecord,
  FactNode,
  KnowledgeEdge,
  RelationshipEdge,
  TickBatch,
} from '@ai-reality/engine';
import { defaultEdge, emptyTickBatch } from '@ai-reality/engine';
import { fixedId, IDS } from '../fixtures/ids.js';

const C = IDS.characters;
const L = IDS.locations;

export const EPOCH_0: EpochRecord = {
  id: IDS.epoch,
  worldId: IDS.world,
  seasonId: IDS.season,
  number: 0,
  status: 'running',
  rngSeed: 'palmiers-test/0',
  rulesVersion: 1,
  lastCommittedTick: -1,
};

export const EPOCH_1: EpochRecord = { ...EPOCH_0, id: fixedId(0, 4), number: 1, rngSeed: 'palmiers-test/1' };

export const jid = {
  scene1: fixedId(0x71, 1),
  scene2: fixedId(0x71, 2),
  presAlexandre: fixedId(0x72, 1),
  presThomas: fixedId(0x72, 2),
  presSarah: fixedId(0x72, 3),
  presAlexandre2: fixedId(0x72, 4),
  interaction1: fixedId(0x73, 1),
  interaction2: fixedId(0x73, 2),
  utterance1: fixedId(0x74, 1),
  utterance2: fixedId(0x74, 2),
  decision1: fixedId(0x75, 1),
  decision2: fixedId(0x75, 2),
  event1: fixedId(0x76, 1),
  event2: fixedId(0x76, 2),
  event3: fixedId(0x76, 3),
  effect1: fixedId(0x77, 1),
  effect2: fixedId(0x77, 2),
  effect3: fixedId(0x77, 3),
  ledger1: fixedId(0x78, 1),
  ledger2: fixedId(0x78, 2),
  score1: fixedId(0x79, 1),
  fact2: fixedId(0x50, 2),
  knowledge2: fixedId(0x60, 2),
};

/** Tick 3 de l'époque 0 : un exemplaire de chaque type d'enregistrement, déjà dans l'ordre de lecture. */
export function tick3Batch(): TickBatch {
  const alexandreSarah: RelationshipEdge = {
    ...defaultEdge(C.alexandre, C.sarah),
    alliance: 15,
    acquaintance: 'met',
    interactionCount: 1,
    labels: ['proposition'],
    extraAxes: { loyaute: 12 },
    firstMetEventId: jid.event1,
    lastInteractionEventId: jid.event2,
  };
  const state: CharacterStateRecord = {
    characterId: C.alexandre,
    epochId: EPOCH_0.id,
    stats: { energy: 70, morale: 55, popularity: 50, influence: 53, reputation: 50 },
    credits: 90,
    status: 'active',
    mood: { hope: 30 },
    scores: { social: 5 },
    runtime: { agenda: [{ kind: 'talk_to', targetId: C.sarah }], position: { kind: 'at', locationId: L.jardin } },
  };
  return {
    ...emptyTickBatch(EPOCH_0.id, 3),
    scenesOpened: [
      {
        id: jid.scene1,
        epochId: EPOCH_0.id,
        locationId: L.jardin,
        zoneId: IDS.zones.banc,
        kind: 'free',
        tickStart: 3,
        tickEnd: null,
      },
    ],
    presencesOpened: [
      {
        id: jid.presAlexandre,
        epochId: EPOCH_0.id,
        characterId: C.alexandre,
        tickStart: 3,
        tickEnd: null,
        kind: 'scene',
        sceneId: jid.scene1,
        fromLocationId: null,
        toLocationId: null,
        offstageReason: null,
        role: 'participant',
      },
      {
        id: jid.presSarah,
        epochId: EPOCH_0.id,
        characterId: C.sarah,
        tickStart: 0,
        tickEnd: null,
        kind: 'offstage',
        sceneId: null,
        fromLocationId: null,
        toLocationId: null,
        offstageReason: 'sommeil',
        role: null,
      },
      {
        id: jid.presThomas,
        epochId: EPOCH_0.id,
        characterId: C.thomas,
        tickStart: 3,
        tickEnd: 4,
        kind: 'transit',
        sceneId: null,
        fromLocationId: L.salon,
        toLocationId: L.jardin,
        offstageReason: null,
        role: null,
      },
    ],
    interactions: [
      {
        id: jid.interaction1,
        epochId: EPOCH_0.id,
        sceneId: jid.scene1,
        type: 'strategic',
        initiatorId: C.alexandre,
        tickStart: 3,
        tickEnd: 4,
        action: 'propose_alliance',
        outcome: 'accepted_conditional',
        mode: 'dialogue',
        classification: { label: 'alliance_proposed_conditional', score: 0.85 },
        participants: [
          { characterId: C.alexandre, role: 'speaker' },
          { characterId: C.sarah, role: 'addressee' },
        ],
      },
      {
        id: jid.interaction2,
        epochId: EPOCH_0.id,
        sceneId: jid.scene1,
        type: 'social',
        initiatorId: null,
        tickStart: 3,
        tickEnd: null,
        action: 'small_talk',
        outcome: null,
        mode: 'summarized',
        classification: null,
        participants: [],
      },
    ],
    utterances: [
      {
        id: jid.utterance1,
        interactionId: jid.interaction1,
        seq: 1,
        tick: 3,
        speakerId: C.alexandre,
        addresseeIds: [C.sarah],
        text: 'On devrait travailler ensemble…',
        intent: 'propose_alliance',
        tone: 'doux',
        emotion: null,
        volume: 'whisper',
        revealedFactIds: [],
        llmCallId: null,
      },
      {
        id: jid.utterance2,
        interactionId: jid.interaction1,
        seq: 2,
        tick: 3,
        speakerId: C.sarah,
        addresseeIds: [C.alexandre],
        text: 'Prouve-moi que je peux te faire confiance.',
        intent: 'set_condition',
        tone: null,
        emotion: 'méfiance',
        volume: 'normal',
        revealedFactIds: [IDS.facts.sarahSecret],
        llmCallId: null,
      },
    ],
    decisions: [
      {
        id: jid.decision1,
        epochId: EPOCH_0.id,
        tick: 3,
        characterId: C.alexandre,
        kind: 'action',
        options: [
          { action: 'propose_alliance', utility: 0.8 },
          { action: 'wait', utility: 0.1 },
        ],
        chosen: { action: 'propose_alliance' },
        policy: 'scripted@1',
        rngDraw: 0.123456789,
        interactionId: jid.interaction1,
        llmCallId: null,
      },
      {
        id: jid.decision2,
        epochId: EPOCH_0.id,
        tick: 3,
        characterId: C.sarah,
        kind: 'outcome',
        options: ['accepted', 'refused'],
        chosen: 'accepted',
        policy: 'scripted@1',
        rngDraw: null,
        interactionId: null,
        llmCallId: null,
      },
    ],
    events: [
      {
        id: jid.event1,
        epochId: EPOCH_0.id,
        tick: 3,
        seq: 1,
        type: 'scene_opened',
        sceneId: jid.scene1,
        interactionId: null,
        locationId: L.jardin,
        payload: { zone: 'banc' },
        importance: 0.3,
        causedByEventId: null,
        participants: [{ characterId: C.alexandre, role: 'actor' }],
      },
      {
        id: jid.event2,
        epochId: EPOCH_0.id,
        tick: 3,
        seq: 2,
        type: 'alliance_proposed',
        sceneId: jid.scene1,
        interactionId: jid.interaction1,
        locationId: L.jardin,
        payload: { conditional: true },
        importance: 0.85,
        causedByEventId: jid.event1,
        participants: [
          { characterId: C.alexandre, role: 'actor' },
          { characterId: C.sarah, role: 'target' },
        ],
      },
    ],
    // Deux effets du même event, volontairement dans un ordre différent de celui des ids.
    effects: [
      {
        id: jid.effect3,
        eventId: jid.event2,
        epochId: EPOCH_0.id,
        tick: 3,
        targetKind: 'relationship',
        characterId: C.sarah,
        otherCharacterId: C.alexandre,
        dimension: 'trust',
        delta: 8,
        valueAfter: 38,
        ruleId: 'alliance.propose',
        ruleVersion: 1,
        reason: 'proposition sincère',
      },
      {
        id: jid.effect1,
        eventId: jid.event2,
        epochId: EPOCH_0.id,
        tick: 3,
        targetKind: 'stat',
        characterId: C.alexandre,
        otherCharacterId: null,
        dimension: 'influence',
        delta: 3,
        valueAfter: 53,
        ruleId: 'alliance.propose',
        ruleVersion: 1,
        reason: null,
      },
      {
        id: jid.effect2,
        eventId: jid.event2,
        epochId: EPOCH_0.id,
        tick: 3,
        targetKind: 'mood',
        characterId: C.alexandre,
        otherCharacterId: null,
        dimension: 'hope',
        delta: 30,
        valueAfter: 30,
        ruleId: 'alliance.propose',
        ruleVersion: 1,
        reason: null,
      },
    ],
    facts: [
      {
        id: jid.fact2,
        subjectId: C.alexandre,
        predicate: 'proposed_alliance_to',
        objectId: C.sarah,
        objectText: null,
        isTrue: true,
        sensitivity: 2,
        originEventId: jid.event2,
        inventedById: null,
      },
    ],
    knowledge: [
      {
        id: jid.knowledge2,
        characterId: C.alexandre,
        factId: jid.fact2,
        sourceType: 'witnessed',
        toldById: null,
        viaEventId: jid.event2,
        parentKnowledgeId: null,
        learnedEpoch: 0,
        learnedTick: 3,
        confidence: 0.7,
        belief: 'believes',
      },
    ],
    ledger: [
      {
        id: jid.ledger1,
        characterId: C.alexandre,
        epochId: EPOCH_0.id,
        eventId: jid.event2,
        amount: -10,
        category: 'special_action',
        source: 'purchased',
      },
      {
        id: jid.ledger2,
        characterId: C.alexandre,
        epochId: EPOCH_0.id,
        eventId: null,
        amount: 25,
        category: 'reward',
        source: 'earned',
      },
    ],
    scoreEntries: [
      {
        id: jid.score1,
        characterId: C.alexandre,
        epochId: EPOCH_0.id,
        eventId: jid.event2,
        score: 'social',
        weight: 1.5,
        impact: 3.3333,
        ruleId: 'alliance.propose',
      },
    ],
    relationships: [alexandreSarah],
    characterStates: [state],
  };
}

/** Tick 4 : ferme la scène et la présence d'Alexandre, puis rouvre une présence dans une nouvelle scène. */
export function tick4Batch(): TickBatch {
  return {
    ...emptyTickBatch(EPOCH_0.id, 4),
    scenesClosed: [{ id: jid.scene1, tickEnd: 4 }],
    presencesClosed: [{ id: jid.presAlexandre, tickEnd: 4 }],
    scenesOpened: [
      {
        id: jid.scene2,
        epochId: EPOCH_0.id,
        locationId: L.salon,
        zoneId: null,
        kind: 'meal',
        tickStart: 4,
        tickEnd: null,
      },
    ],
    presencesOpened: [
      {
        id: jid.presAlexandre2,
        epochId: EPOCH_0.id,
        characterId: C.alexandre,
        tickStart: 4,
        tickEnd: null,
        kind: 'scene',
        sceneId: jid.scene2,
        fromLocationId: null,
        toLocationId: null,
        offstageReason: null,
        role: 'participant',
      },
    ],
  };
}

export const SARAH_SECRET: FactNode = {
  id: IDS.facts.sarahSecret,
  subjectId: C.sarah,
  predicate: 'hides',
  objectId: null,
  objectText: 'a déjà participé à une autre émission',
  isTrue: true,
  sensitivity: 3,
  originEventId: null,
  inventedById: null,
};

/** Chaîne de 4 maillons : Alexandre (témoin) → Sarah → Léa → Thomas. */
export function chainOf4(factId: string): KnowledgeEdge[] {
  const link = (rank: number, characterId: string, toldById: string | null, parent: number | null): KnowledgeEdge => ({
    id: fixedId(0x61, rank),
    characterId,
    factId,
    sourceType: toldById === null ? 'witnessed' : 'told',
    toldById,
    viaEventId: null,
    parentKnowledgeId: parent === null ? null : fixedId(0x61, parent),
    learnedEpoch: 0,
    learnedTick: rank,
    confidence: toldById === null ? 1 : 0.9 ** rank,
    belief: 'believes',
  });
  return [
    link(1, C.alexandre, null, null),
    link(2, C.sarah, C.alexandre, 1),
    link(3, C.lea, C.sarah, 2),
    link(4, C.thomas, C.lea, 3),
  ];
}
